# Generated by Django 2.0.2 on 2018-07-22 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='received',
            field=models.ManyToManyField(related_name='player_handouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmember',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='campaigns.Campaign'),
        ),
        migrations.AddField(
            model_name='campaignmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='members',
            field=models.ManyToManyField(related_name='campaigns', through='campaigns.CampaignMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
