# Generated by Django 2.0.2 on 2018-07-09 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(default='1', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='handout',
            name='name',
            field=models.CharField(default='1', max_length=64, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
    ]
