# Generated by Django 2.0.2 on 2018-07-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20180722_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignmember',
            old_name='user',
            new_name='member',
        ),
    ]
